"""
Utilities for generating a synthetic dataset tailored for the Suna pipeline.

The original Suna prototype relied on synthetic data to demonstrate bootstrap
confounder discovery.  This module recreates that experience inside SEEKER by
producing a reproducible dataset and metadata pair that plug directly into the
standard ingestion flow (`dataset_examples/` + `DataLoader`).
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass, asdict
from hashlib import sha256
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import pandas as pd

SYNTHETIC_DATASET_NAME = "suna_synthetic"
CSV_SUFFIX = ".csv"
METADATA_SUFFIX = "_metadata.json"


@dataclass(frozen=True)
class SyntheticDatasetSpec:
    """Configuration describing the synthetic data generating process."""

    n_samples: int = 2000
    seed: int = 7
    treatment_intercept: float = -0.3
    treatment_beta_conf1: float = 1.2
    treatment_beta_conf2: float = 0.9
    treatment_beta_instrument: float = 0.6
    outcome_base: float = 0.5
    ate: float = 1.5
    outcome_beta_conf1: float = 2.0
    outcome_beta_conf2: float = 1.3
    outcome_beta_instrument: float = 0.2
    noise_std: float = 1.0


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-x))


def _generate_dataframe(spec: SyntheticDatasetSpec) -> pd.DataFrame:
    rng = np.random.default_rng(spec.seed)
    confounder_1 = rng.normal(0.0, 1.0, size=spec.n_samples)
    confounder_2 = rng.normal(0.0, 1.0, size=spec.n_samples)
    instrument = rng.normal(0.0, 1.0, size=spec.n_samples)
    proxy = 0.7 * confounder_1 + 0.2 * rng.normal(0.0, 1.0, size=spec.n_samples)
    seasonal = np.sin(np.linspace(0, 2 * math.pi, spec.n_samples))
    linear_trend = np.linspace(0.0, 1.0, spec.n_samples)

    logits = (
        spec.treatment_intercept
        + spec.treatment_beta_conf1 * confounder_1
        + spec.treatment_beta_conf2 * confounder_2
        + spec.treatment_beta_instrument * instrument
    )
    treatment_prob = _sigmoid(logits)
    treatment = rng.binomial(1, treatment_prob)

    noise = rng.normal(0.0, spec.noise_std, size=spec.n_samples)
    outcome = (
        spec.outcome_base
        + spec.ate * treatment
        + spec.outcome_beta_conf1 * confounder_1
        + spec.outcome_beta_conf2 * confounder_2
        + spec.outcome_beta_instrument * instrument
        + 0.5 * proxy
        + 0.3 * seasonal
        + 0.2 * linear_trend
        + noise
    )

    df = pd.DataFrame(
        {
            "treatment": treatment,
            "outcome": outcome,
            "confounder_1": confounder_1,
            "confounder_2": confounder_2,
            "instrument": instrument,
            "proxy": proxy,
            "seasonal_component": seasonal,
            "linear_trend": linear_trend,
            "noise": noise,
        }
    )
    return df


def _build_metadata(df: pd.DataFrame, spec: SyntheticDatasetSpec) -> Dict[str, object]:
    csv_preview = df.head(100).to_csv(index=False).encode("utf-8")
    checksum = sha256(csv_preview).hexdigest()

    metadata: Dict[str, object] = {
        "dataset_name": SYNTHETIC_DATASET_NAME,
        "description": (
            "Synthetic dataset generated for Suna confounder discovery demos. "
            "It contains known confounders that influence both treatment "
            "assignment and outcomes, an instrumental variable, and nuisance "
            "features used to test bootstrap selection heuristics."
        ),
        "columns": list(df.columns),
        "row_count": len(df),
        "generator": asdict(spec),
        "checksum": {
            "sha256_first100": checksum,
            "note": "Hash computed from the first 100 rows to provide a lightweight fingerprint.",
        },
        "tags": ["synthetic", "causal", "suna"],
        "source": "Programmatically generated by seeker.src.suna.synthetic",
        "suna": {
            "treatment_column": "treatment",
            "outcome_column": "outcome",
            "candidate_covariates": [
                "confounder_1",
                "confounder_2",
                "instrument",
                "proxy",
                "seasonal_component",
                "linear_trend",
            ],
            "tau": 0.05,
            "n_boot": 100,
            "default_method": "bcd",
            "random_state": spec.seed,
        },
    }
    return metadata


def ensure_synthetic_dataset(
    data_dir: Path | str = Path("dataset_examples"),
    *,
    spec: SyntheticDatasetSpec | None = None,
    force: bool = False,
) -> Tuple[Path, Path]:
    """
    Guarantee that the synthetic dataset + metadata exist in ``data_dir``.

    Returns the paths to the CSV and metadata files.  Files are regenerated
    when they are missing or when ``force`` is set to ``True``.
    """
    spec = spec or SyntheticDatasetSpec()
    data_dir = Path(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)

    csv_path = data_dir / f"{SYNTHETIC_DATASET_NAME}{CSV_SUFFIX}"
    metadata_path = data_dir / f"{SYNTHETIC_DATASET_NAME}{METADATA_SUFFIX}"

    if not csv_path.exists() or not metadata_path.exists() or force:
        df = _generate_dataframe(spec)
        df.to_csv(csv_path, index=False)
        metadata = _build_metadata(df, spec)
        metadata_path.write_text(json.dumps(metadata, indent=2))

    return csv_path, metadata_path


__all__ = [
    "SYNTHETIC_DATASET_NAME",
    "SyntheticDatasetSpec",
    "ensure_synthetic_dataset",
]
